$schema: https://azuremlschemas.azureedge.net/latest/batchDeployment.schema.json
endpoint_name: imagenet-classifier-batch
name: imagenet-classifier-resnetv2
description: A ResNetV2 model architecture for performing ImageNet classification in batch
model: azureml:imagenet-classifier@latest
compute: azureml:cpu-cluster
environment:
   image: mcr.microsoft.com/azureml/openmpi4.1.0-cuda11.1-cudnn8-ubuntu20.04:latest
   conda_file: ./imagenet-classifier/environment/conda.yml
code_configuration:
  code: ./code/
  scoring_script: batch_driver.py
resources:
  instance_count: 2
max_concurrency_per_instance: 1
mini_batch_size: 5
output_action: append_row
output_file_name: predictions.csv
retry_settings:
  max_retries: 3
  timeout: 300
error_threshold: -1
logging_level: info